[directory]
truncation_length = 100
truncate_to_repo = false
style = "yellow"
format = "[:$path]($style)[$read_only]($read_only_style) "

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'


